export const MOCK_QUESTIONS = [
  {
    id: 'q1',
    type: 'mcq',
    parts: [{ type: 'text', content: 'What is the capital of France?' }],
    options: ['London', 'Paris', 'Berlin', 'Madrid'],
    correctAnswerIndex: 1,
    solution: 'Paris is the capital city of France.',
    difficulty: 'easy',
    isMultiSelect: false,
    isVertical: false,
    showSubmitButton: false,
    sortOrder: 1,
  },
  {
    id: 'q2',
    type: 'imageChoice',
    parts: [{ type: 'text', content: 'Which shape is a circle?' }],
    options: [
      'https://cdn-icons-png.flaticon.com/512/3105/3105807.png',
      'https://cdn-icons-png.flaticon.com/512/2618/2618245.png',
      'https://cdn-icons-png.flaticon.com/512/5974/5974636.png',
    ],
    correctAnswerIndex: 0,
    solution: 'A circle is a round shape with no corners.',
    difficulty: 'easy',
    isMultiSelect: false,
    isVertical: false,
    showSubmitButton: false,
    sortOrder: 2,
  },
  {
    id: 'q3',
    type: 'textInput',
    parts: [{ type: 'text', content: 'What is 5 + 3?' }],
    correctAnswerText: '8',
    solution: '5 + 3 equals 8.',
    difficulty: 'easy',
    showSubmitButton: true,
    sortOrder: 3,
  },
  {
    id: 'q4',
    type: 'fillInTheBlank',
    parts: [
      { type: 'text', content: 'The quick ' },
      { type: 'blank', id: 'blank1' },
      { type: 'text', content: ' fox jumps over the ' },
      { type: 'blank', id: 'blank2' },
      { type: 'text', content: ' dog.' },
    ],
    correctAnswerText: '{"blank1":"brown","blank2":"lazy"}',
    solution: "The complete phrase is: 'The quick brown fox jumps over the lazy dog.'",
    difficulty: 'medium',
    showSubmitButton: true,
    sortOrder: 4,
  },
  {
    id: 'q5',
    type: 'mcq',
    parts: [{ type: 'text', content: 'Which of these are primary colors? (Select all that apply)' }],
    options: ['Red', 'Green', 'Blue', 'Yellow', 'Purple'],
    correctAnswerIndices: [0, 2, 3],
    solution: 'The primary colors are Red, Blue, and Yellow.',
    difficulty: 'medium',
    isMultiSelect: true,
    isVertical: false,
    showSubmitButton: true,
    sortOrder: 5,
  },
  {
    id: 'q6',
    type: 'imageChoice',
    parts: [{ type: 'text', content: 'In which scenario do particles have higher kinetic energy?' }],
    options: [
      'https://cdn-icons-png.flaticon.com/512/3105/3105807.png',
      'https://cdn-icons-png.flaticon.com/512/2618/2618245.png',
    ],
    correctAnswerIndex: 0,
    solution: 'Higher temperature means more kinetic energy.',
    difficulty: 'medium',
    isMultiSelect: false,
    isVertical: true,
    showSubmitButton: false,
    sortOrder: 6,
  },
  {
    id: 'q7',
    type: 'textInput',
    parts: [{ type: 'text', content: 'How many days are in a week?' }],
    correctAnswerText: '7',
    solution: 'There are 7 days in a week.',
    difficulty: 'easy',
    showSubmitButton: true,
    sortOrder: 7,
  },
  {
    id: 'q8',
    type: 'sorting',
    parts: [{ type: 'text', content: 'Arrange these numbers from smallest to largest:' }],
    items: [
      { id: 'item1', content: '25', correctPosition: 1 },
      { id: 'item2', content: '8', correctPosition: 0 },
      { id: 'item3', content: '100', correctPosition: 3 },
      { id: 'item4', content: '42', correctPosition: 2 },
    ],
    correctAnswerText: '["item2","item1","item4","item3"]',
    solution: 'The correct order from smallest to largest is: 8, 25, 42, 100.',
    difficulty: 'medium',
    showSubmitButton: true,
    sortOrder: 8,
  },
  {
    id: 'q9',
    type: 'dragAndDrop',
    parts: [{ type: 'text', content: 'Match each animal to its group:' }],
    dragItems: [
      { id: 'cat', content: 'Cat', imageUrl: 'https://cdn-icons-png.flaticon.com/512/2138/2138440.png', targetGroupId: 'mammals' },
      { id: 'eagle', content: 'Eagle', imageUrl: 'https://cdn-icons-png.flaticon.com/512/2405/2405471.png', targetGroupId: 'birds' },
      { id: 'dog', content: 'Dog', imageUrl: 'https://cdn-icons-png.flaticon.com/512/2138/2138166.png', targetGroupId: 'mammals' },
      { id: 'parrot', content: 'Parrot', imageUrl: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png', targetGroupId: 'birds' },
    ],
    dropGroups: [
      { id: 'mammals', label: 'Mammals' },
      { id: 'birds', label: 'Birds' },
    ],
    solution: 'Cats and dogs are mammals. Eagles and parrots are birds.',
    difficulty: 'medium',
    showSubmitButton: true,
    sortOrder: 9,
  },
];
